//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.11 at 05:17:57 PM AEST 
//


package org.datacite.schema.kernel_4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="resourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Audiovisual"/>
 *     &lt;enumeration value="Award"/>
 *     &lt;enumeration value="Book"/>
 *     &lt;enumeration value="BookChapter"/>
 *     &lt;enumeration value="Collection"/>
 *     &lt;enumeration value="ComputationalNotebook"/>
 *     &lt;enumeration value="ConferencePaper"/>
 *     &lt;enumeration value="ConferenceProceeding"/>
 *     &lt;enumeration value="DataPaper"/>
 *     &lt;enumeration value="Dataset"/>
 *     &lt;enumeration value="Dissertation"/>
 *     &lt;enumeration value="Event"/>
 *     &lt;enumeration value="Image"/>
 *     &lt;enumeration value="Instrument"/>
 *     &lt;enumeration value="InteractiveResource"/>
 *     &lt;enumeration value="Journal"/>
 *     &lt;enumeration value="JournalArticle"/>
 *     &lt;enumeration value="Model"/>
 *     &lt;enumeration value="OutputManagementPlan"/>
 *     &lt;enumeration value="PeerReview"/>
 *     &lt;enumeration value="PhysicalObject"/>
 *     &lt;enumeration value="Preprint"/>
 *     &lt;enumeration value="Project"/>
 *     &lt;enumeration value="Report"/>
 *     &lt;enumeration value="Service"/>
 *     &lt;enumeration value="Software"/>
 *     &lt;enumeration value="Sound"/>
 *     &lt;enumeration value="Standard"/>
 *     &lt;enumeration value="StudyRegistration"/>
 *     &lt;enumeration value="Text"/>
 *     &lt;enumeration value="Workflow"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "resourceType")
@XmlEnum
public enum ResourceType {

    @XmlEnumValue("Audiovisual")
    AUDIOVISUAL("Audiovisual"),
    @XmlEnumValue("Award")
    AWARD("Award"),
    @XmlEnumValue("Book")
    BOOK("Book"),
    @XmlEnumValue("BookChapter")
    BOOK_CHAPTER("BookChapter"),
    @XmlEnumValue("Collection")
    COLLECTION("Collection"),
    @XmlEnumValue("ComputationalNotebook")
    COMPUTATIONAL_NOTEBOOK("ComputationalNotebook"),
    @XmlEnumValue("ConferencePaper")
    CONFERENCE_PAPER("ConferencePaper"),
    @XmlEnumValue("ConferenceProceeding")
    CONFERENCE_PROCEEDING("ConferenceProceeding"),
    @XmlEnumValue("DataPaper")
    DATA_PAPER("DataPaper"),
    @XmlEnumValue("Dataset")
    DATASET("Dataset"),
    @XmlEnumValue("Dissertation")
    DISSERTATION("Dissertation"),
    @XmlEnumValue("Event")
    EVENT("Event"),
    @XmlEnumValue("Image")
    IMAGE("Image"),
    @XmlEnumValue("Instrument")
    INSTRUMENT("Instrument"),
    @XmlEnumValue("InteractiveResource")
    INTERACTIVE_RESOURCE("InteractiveResource"),
    @XmlEnumValue("Journal")
    JOURNAL("Journal"),
    @XmlEnumValue("JournalArticle")
    JOURNAL_ARTICLE("JournalArticle"),
    @XmlEnumValue("Model")
    MODEL("Model"),
    @XmlEnumValue("OutputManagementPlan")
    OUTPUT_MANAGEMENT_PLAN("OutputManagementPlan"),
    @XmlEnumValue("PeerReview")
    PEER_REVIEW("PeerReview"),
    @XmlEnumValue("PhysicalObject")
    PHYSICAL_OBJECT("PhysicalObject"),
    @XmlEnumValue("Preprint")
    PREPRINT("Preprint"),
    @XmlEnumValue("Project")
    PROJECT("Project"),
    @XmlEnumValue("Report")
    REPORT("Report"),
    @XmlEnumValue("Service")
    SERVICE("Service"),
    @XmlEnumValue("Software")
    SOFTWARE("Software"),
    @XmlEnumValue("Sound")
    SOUND("Sound"),
    @XmlEnumValue("Standard")
    STANDARD("Standard"),
    @XmlEnumValue("StudyRegistration")
    STUDY_REGISTRATION("StudyRegistration"),
    @XmlEnumValue("Text")
    TEXT("Text"),
    @XmlEnumValue("Workflow")
    WORKFLOW("Workflow"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ResourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResourceType fromValue(String v) {
        for (ResourceType c: ResourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
