//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.04 at 12:06:16 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datacite.org/schema/kernel-2.2", xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI = "http://datacite.org/schema/kernel-2.2")}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.datacite.schema.kernel_2;
