drop table acl_entry;
drop table acl_object_identity;
drop table acl_class;
drop table acl_sid;
drop table authorities;
drop table users;
drop table fedora_object;
drop table groups;
drop table domains;